Large scale cleanup and restructuring to generalize for more than just -intel, and to integrate with other tools.

diff --git a/hist-pkg b/hist-pkg
--- a/hist-pkg
+++ b/hist-pkg
@@ -2,73 +2,40 @@
 
 # Include the bash library functions
 . $(dirname $0)/xorg-pkg-tools.lib
-# TODO:  Incorporate the general routines from the .lib into here
 
-if [ ! -d hist-snap ]; then
-    mkdir hist-snap
+# TODO:  Load this from a user config file
+AUTOSIGN=${AUTOSIGN:-55955A6B}
+
+usage() {
+    write_msg "Usage: $0 <commits-file> <debian-dir>"
+    exit 1
+}
+
+# Handle command-line parameters
+COMMITS_FILE=$1
+DEBIAN_DIR=$2
+[ -z "${COMMITS_FILE}" ] && usage
+[ -z "${DEBIAN_DIR}" ] && usage
+
+PKG=${COMMITS_FILE%.commits}
+if [ ! -e "${PKG}.config" ] ; then
+   echo "Error:  Cannot find ${PKG}.config."
+   exit 1
+fi
+. ${PKG}.config
+
+BASEDIR=$(dirname "${COMMITS_FILE}")
+if [ ! -d ${BASEDIR} ]; then
+    die "directory ${BASEDIR} not found"
 fi
 
-# TODO:  Take commits.lst as an input parameter
-for commit in $(cat commits.lst) ; do
-    echo -n "Processing $commit"
-    git_pkg $commit > bisect/$commit-pkg.log 2>&1
-    if [ $? == 0 ]; then
-        echo " succeeded"
-    else
-        echo " failed"
-    fi
-done
+REPO="${BASEDIR}/${GIT_DIR}"
 
-# TODO:  Break this up into better sub-functions
-git_pkg() {
-    # Given git commit id
-    COMMIT=$1
-    if [ -z "${COMMIT}" ]; then
-        echo "Usage: $0 <commit-id>"
-        exit 1
-    fi
-
-    # TODO:  Use the package config file to get these parameters
-    PACKAGE=xserver-xorg-video-intel
-    REPO=${REPO:-~/src/xserver-xorg-video-intel/xf86-video-intel/}
-    EPOCH='2:'
-    ADDVERSION="-1"
+# Constructs a version string for a given version control system commit
+vcs_snapshot_version_string() {
+    VCS_TYPE=$1
+    COMMIT=$2
     DATE_PREFIX="+"
-
-    # These should be input parameters
-    DEBIAN=${DEBIAN:-~/src/${PACKAGE}/debian}
-    DISTRIBUTION=${DISTRIBUTION:-hardy}
-
-    # TODO:  Load this from a user config file
-    AUTOSIGN=${AUTOSIGN:-55955A6B}
-
-    cd $REPO
-
-    BASEDIR=$(dirname $REPO)/hist-snap
-    ORIGDIR=${REPO%/*}.orig
-    
-    if [ ! -d ${BASEDIR} ]; then
-        echo "mkdir -p ${BASEDIR}"
-        mkdir -p ${BASEDIR}
-    fi
-
-    # Update the git repository to the commit id
-    git reset --hard $COMMIT
-    date=$(git log | head | grep Date | head -n 1| sed -e "s/Date: *//" | sed -e "s/[\+\-].*$//")
-    DATE=`date +%Y%m%d -d "$date"`
-
-    # Copy to new working directory
-    if [ -e ${ORIGDIR} ]; then
-        echo "Removing existing ${ORIGDIR}"
-        rm -rf ${ORIGDIR}
-    fi
-    echo "cp -a ${REPO} ${ORIGDIR}"
-    cp -a ${REPO} ${ORIGDIR}
-
-    # TODO:  This should be a package option whether to do this
-    # Update autoconfage
-    cd ${ORIGDIR}
-    ./autogen.sh
 
     # Get the released package version for this branch
     if [ -z "$PACKAGE_VERSION" ]; then
@@ -76,46 +43,98 @@ git_pkg() {
     fi
     [ -z "$PACKAGE_VERSION" ] && die "No PACKAGE_VERSION in configure"
 
+    # Get the date for the most recent git commit
+    DATE=git_last_commit_date
+
+    echo "${PACKAGE_VERSION}${DATE_PREFIX}${VCS_TYPE}${DATE}.${COMMIT}"
+}
+
+
+# Generate a package from an upstream commit, for a given
+# distro version and a given debian directory
+git_pkg() {
+    COMMIT=$1
+    DEBIAN=$2
+
+    echo "COMMIT:  $COMMIT"
+    echo "DEBIAN:  $DEBIAN"
+    echo "REPO:    $REPO"
+
+    # Update the git repository to the commit id
+    cd ${REPO}
+    git reset --hard $COMMIT
+
+    ORIGDIR=${REPO}.orig
+    echo "Origdir: $ORIGDIR"
+
+    # Copy to new working directory
+    copy_dir ${REPO} ${ORIGDIR}
+    cd ${ORIGDIR}
+    return
+
+    # Update autoconfage if desired
+    [ ${UPDATE_AUTOCONF} ] && ./autogen.sh
+
     # Set the version string
-    GITVER="${PACKAGE_VERSION}${DATE_PREFIX}git${DATE}.${COMMIT}"
-    echo $GITVER
+    GITVER=`vcs_snapshot_version_string "git" $COMMIT`
+    msg $GITVER
 
     # Create the source dir
-    SOURCE=${BASEDIR}/${PACKAGE}-${GITVER}.orig
-    if [ -e $SOURCE ]; then
-        echo "Removing existing $SOURCE dir"
-        rm -rf ${SOURCE}
-    fi
-    echo "mv ${ORIGDIR} ${SOURCE}"
-    mv ${ORIGDIR} ${SOURCE}
+    SOURCE=${BASEDIR}/${PKG}-${GITVER}.orig
+    copy_dir ${ORIGDIR} ${SOURCE}
+    rm -rf ${ORIGDIR}
+
+    # TODO:  Remove autom4te, cache, .git, etc.
+    # TODO:  Doesn't the tarball need generated at this point?
+    # TODO:  Above this line should be one function, below another
 
     # Create the target dir
-    TARGET=${BASEDIR}/${PACKAGE}-${GITVER}
-    if [ -e ${TARGET} ]; then
-        echo "Removing existing ${TARGET}"
-        rm -rf ${TARGET}
-    fi
-    echo "cp -a ${SOURCE} ${TARGET}"
-    cp -a ${SOURCE} ${TARGET}
+    TARGET=${BASEDIR}/${PKG}-${GITVER}
+    copy_dir ${SOURCE} ${TARGET}
     cd ${TARGET}
 
     # Copy in the given debian/ directory
-    if [ -e ${TARGET}/debian ]; then
-        echo "Error:  ${TARGET}/debian already exists!"
-        exit 1
-    fi
-    echo "cp -a ${DEBIAN} ${TARGET}"
-    cp -a ${DEBIAN} ${TARGET}
+    copy_dir ${DEBIAN} ${TARGET}/
 
     # Add changelog entry
-    echo "Adding changelog entry via dch..."
-    dch -b --distribution $DISTRIBUTION --newversion ${EPOCH}${GITVER}${ADDVERSION} "Checkout from git up to $COMMIT ($date)" || die "dch: $?"
-    
+    msg "Adding changelog entry via dch..."
+    dch -b --distribution UNRELEASED --newversion \
+        ${EPOCH}${GITVER}${ADDVERSION} \
+        "Checkout from git up to $COMMIT ($date)" \
+        || die "dch: $?"
+
     # Create package
-    pwd
-    echo "debuild -sa -S"
+    msg "debuild -sa -S"
     debuild -sa -S -k${AUTOSIGN}
 
-    # TODO:  Generate JSON output file
-    echo "" > ${TARGET}.json
+    # Generate JSON output file
+    echo  > ${TARGET}.json <<EOF
+{
+    "pkg":          "${PKG}",
+    "commit":       "${COMMIT}",
+    "date":         "${DATE}",
+    "debian":       "${DEBIAN}",
+    "source":       "${SOURCE}",
+    "target":       "${TARGET}",
+    "dependencies": ""
 }
+EOF
+}
+
+exec < ${COMMITS_FILE}
+while read commit ; do
+    [ -z "${commit}" ] && continue
+
+    echo "Processing $commit..."
+    continue
+    git_pkg ${commit} ${DEBIAN_DIR} | tee ${BASEDIR}/$commit-pkg.log 2>&1
+    if [ $? = 0 ]; then
+        msg "Processing $commit succeeded"
+        msg ""
+    else
+        msg "Processing $commit failed"
+        msg ""
+    fi
+
+done
+
