lts-stack: remove some hardcoded dependencies

diff --git a/lts-libdrm-rename b/lts-libdrm-rename
--- a/lts-libdrm-rename
+++ b/lts-libdrm-rename
@@ -13,9 +13,17 @@ eval $(grep ^lts_codename= "${basedir}/lts-pkg-rename")
 eval $(grep ^codename= "${basedir}/lts-pkg-rename")
 eval $(grep ^suffix= "${basedir}/lts-pkg-rename")
 eval $(grep ^extraversion= "${basedir}/lts-pkg-rename")
+
+mapping="$1"
+
 new_package=libdrm-${suffix}
 old_package=libdrm
 old_binaries="libkms1 2 -intel1 -nouveau2 -omap1 -radeon1"
+ltsq=$(grep "^libdrm-intel1" "${mapping}" | cut -d- -f3)
+if [ -z "${ltsq}" ]; then
+    echo "Could not get name for ltsq"
+    exit 1
+fi
 
 # debian/control
 
@@ -23,7 +31,7 @@ old_binaries="libkms1 2 -intel1 -nouveau2 -omap1 -radeon1"
 ${basedir}/dpkg-control \
     --source-suffix ${suffix} \
     --binary-suffix ${suffix} \
-    --mapping-file "${basedir}/lts-pkg-mapping.txt" \
+    --mapping-file "${mapping}" \
     --kill-binaries "libdrm2-udeb,libdrm-nouveau1a,libdrm-nouveau1a-dbg" \
     > debian/control.new
 
@@ -53,13 +61,13 @@ sed -e "/libdrm_nouveau/d" -i debian/rules.new
 
 # big mess, since we're special
 mv debian/libdrm-dev.install debian/libdrm-dev-${suffix}.install
-sed -e "s/^lib.../&-ltsq/" -i debian/*.lintian-overrides
+sed -e "s/^lib.../&-${ltsq}/" -i debian/*.lintian-overrides
 
 for pkg in ${old_binaries}; do
     if [ "${pkg}" = "libkms1" ]; then
-        newpkg="libkms-ltsq1"
+        newpkg="libkms-${ltsq}1"
     else
-        newpkg="libdrm-ltsq${pkg}"
+        newpkg="libdrm-${ltsq}${pkg}"
         pkg="libdrm${pkg}"
     fi
 
@@ -101,12 +109,12 @@ for pkg in ${old_binaries}; do
     sed -e "s/ ${pkg} / ${newpkg} /" -i "debian/${newpkg}.symbols"
 
     # we're renaming the sonames too, fix those up..
-    sed -e "s/^libdrm/libdrm_ltsq/" -i "debian/${newpkg}.symbols"
-    sed -e "s/^libkms/libkms_ltsq/" -i "debian/${newpkg}.symbols"
+    sed -e "s/^libdrm/libdrm_${ltsq}/" -i "debian/${newpkg}.symbols"
+    sed -e "s/^libkms/libkms_${ltsq}/" -i "debian/${newpkg}.symbols"
 
     # and of course the install stuff
-    sed -e "s/libdrm/libdrm_ltsq/" -i "debian/${newpkg}.install"
-    sed -e "s/libkms/libkms_ltsq/" -i "debian/${newpkg}.install"
+    sed -e "s/libdrm/libdrm_${ltsq}/" -i "debian/${newpkg}.install"
+    sed -e "s/libkms/libkms_${ltsq}/" -i "debian/${newpkg}.install"
 done
 
 mv debian/rules.new debian/rules
@@ -116,18 +124,18 @@ sed -e "/04_libdrm-2.4.37-nouveau-1.diff/d" -e "/02_build_libkms_against_in_tree
 # libdrm is being renamed, so make sure libkms links against it
 patch -Np1 < debian/patches/02_build_libkms_against_in_tree_drm.diff
 
-sed -e "s/-lkms/&_ltsq/" -e "s/-ldrm/&_ltsq/" -i libdrm.pc.in */*.pc.in
+sed -e "s/-lkms/&_${ltsq}/" -e "s/-ldrm/&_${ltsq}/" -i libdrm.pc.in */*.pc.in
 
-sed -e "s/^libdrm/&_ltsq/" -i Makefile.am
-sed -e "s/^libkms/&_ltsq/g" -i libkms/Makefile.am
-sed -e "s/libkms\\.la/libkms_ltsq.la/" \
-    -e "s/libdrm\\.la/libdrm_ltsq.la/" \
+sed -e "s/^libdrm/&_${ltsq}/" -i Makefile.am
+sed -e "s/^libkms/&_${ltsq}/g" -i libkms/Makefile.am
+sed -e "s/libkms\\.la/libkms_${ltsq}.la/" \
+    -e "s/libdrm\\.la/libdrm_${ltsq}.la/" \
     -i Makefile.am tests/Makefile.am tests/*/Makefile.am libkms/Makefile.am
 
 for n in exynos intel nouveau omap radeon; do
-    sed -e "s/^libdrm/&_ltsq/" \
-        -e "s/libdrm_${n}\\.la/libdrm_ltsq_${n}.la/" \
-        -e "s/libdrm\\.la/libdrm_ltsq.la/" \
+    sed -e "s/^libdrm/&_${ltsq}/" \
+        -e "s/libdrm_${n}\\.la/libdrm_${ltsq}_${n}.la/" \
+        -e "s/libdrm\\.la/libdrm_${ltsq}.la/" \
         -i ${n}/Makefile.am
 done
 
